- name: Disable NTLM authentication
  hosts: domain_controllers
  gather_facts: no
  tasks:
    - name: Deny NTLM authentication
      ansible.windows.win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: RestrictSendingNTLMTraffic
        data: 2
        type: dword
